#!/usr/bin/env python
# coding: utf-8

def build(ctx):
    src_dir = ctx.path.parent.find_dir('test/')
    inc_dir = ctx.path.find_dir('../include')
    ctx.add_group('group9')
    ctx.add_group('group10')
    ctx.add_group('group11')
    
    ctx.set_group('group9')
    for src in ctx.path.ant_glob('*.cc'):
        ctx(features='cxx cxxprogram',
                source=src,
                includes=[inc_dir,src_dir],
                lib=ctx.env.LIB_NTL + ctx.env.LIB_GMP,
                stlib=ctx.env.STLIB_NTL + ctx.env.STLIB_GMP,
                target=src.name[:-3],
                use=['latticetester'],
                install_path='${BINDIR}/test')

    ctx.set_group('group10')
    for src in ctx.path.ant_glob('build/test/*.o'):
        ctx(rule='rm ${SRC}',
                source=src,
                target=src.name[:],
                use=src.name[:-6] + 'cc',
                install_path='${BINDIR}/test')
        
    ctx.set_group('group11')
    for src in ctx.path.ant_glob('*.dat'):
        ctx(rule='cp ${SRC} ${TGT}',
                source=src,
                target=src.name[:],
                install_path='${BINDIR}/test')

    for src in ctx.path.ant_glob('*.zip'):
        ctx(rule='cp ${SRC} ${TGT}',
                source=src,
                target=src.name[:],
                install_path='${BINDIR}/test')
